template: true   # required for local templates
valuesFilePath: ./valuess.yml

pipelines:
  - name: my_first_pipeline
    steps:
      - name: p1_s1
        type: Bash
        execution:
          onStart:
            - echo "Preparing for work..."
          onExecute:
            - printenv
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"